# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juice', '0005_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(default='', upload_to='stores'),
            preserve_default=False,
        ),
    ]
