# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juice', '0007_auto_20170705_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('last_login_time', models.DateTimeField(auto_now_add=True)),
                ('wx_openid', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juice.Customer')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_state',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_state',
            field=models.IntegerField(default=1),
        ),
    ]
